<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HarithaPC" name="Default test" tests="2" failures="0" timestamp="26 Apr 2018 21:16:16 GMT" time="24.641" errors="0">
  <testcase name="@AfterClass afterTest" time="0.0" classname="com.mosaicsmartdata.technicaltest.tests.LoginTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:

 Logout is UnSuccessful for user : validusername ; Expecting to logout, 
 Login is Successful for user : invalidusername ; Expecting login Error">
      <![CDATA[java.lang.AssertionError: The following asserts failed:

 Logout is UnSuccessful for user : validusername ; Expecting to logout, 
 Login is Successful for user : invalidusername ; Expecting login Error
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:37)
	at com.mosaicsmartdata.technicaltest.tests.LoginTest.afterTest(LoginTest.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:225)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:114)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @AfterClass afterTest -->
  <testcase name="logintest" time="17.602" classname="com.mosaicsmartdata.technicaltest.tests.LoginTest"/>
  <testcase name="logintest" time="4.758" classname="com.mosaicsmartdata.technicaltest.tests.LoginTest"/>
</testsuite> <!-- Default test -->
